name: "Handle Submission"
on:
  repository_dispatch:
    types: handle-submission

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install dependencies
        run: npm install
            npm install fs
      - name: Process input
        run: |
          node actions/process-input.js
      - name: Run prettier
        run: |
          npx prettier "./*.json" --write
      - name: Push to github
        uses: actions-x/commit@v2
        with:
          token: ${{ secrets.GH_TOKEN_PERSONAL }}